### ISSUE TITLE
selected color

### ISSUE THREAD

**Issue by eachann1026** [ahmadawais/shades-of-purple-vscode#23]
![FeVlVg.png](https://s1.ax1x.com/2018/11/29/FeVlVg.png)

**Comment by eachann1026** [comment]
You can't tell I picked it?

**Comment by ahmadawais** [comment]
@eachann1026 you're going to have to be more specific than that. 

Here' I just tested it in a `.html` file.

![image](https://on.ahmda.ws/8aacf2/c)

The select highlight color is just fine. If you don't see the same then reload your VSCode it happens to go stale sometimes which is not a theme issue. If it's still there, some extension could be the cause here.

I am happy to help.

Peace! ✌️
