### ISSUE TITLE
Single backquotes and triple backquotes in Markdown mode

### ISSUE THREAD

**Issue by ykomatsu** [ahmadawais/shades-of-purple-vscode#25]
![Markdown](https://photos.smugmug.com/Images/i-RwvxFV6/0/0b4c3a02/Th/2018-12-11-markdown-Th.png)

In Markdown mode, single backquotes(`` ` ``) and triple backquotes(```` ``` ````) are difficult to see.
I think that these characters should not be so noticeable but these colors are too difficult to see.

**Comment by ahmadawais** [comment]
Actually, that's intentional. There are just five different punctuations that are dimmed to be ignored while writing Markdown. 

I talked about it in the video here → https://youtu.be/wZ1nzNCD-iM?t=62 
Watch my reasoning of having these weird syntax fade away. I do my writing in markdown with VSCode for a lot of things. I don't like the syntax that makes it look weird.

The color chosen here is the same one you see for tabs/spaces indicators. Now you don't need a strong color to indicate that there is a tab here or space.

Check it's the same color

![image](https://on.ahmda.ws/88693e/c)

So, you can safely ignore this syntax and focus on what matters.

Peace! ✌️

**Comment by comilao** [comment]
I really like the theme, I have been using it for about a year. But I am also struggling to see the triple backquotes (` ``` `) as mentioned by @ykomatsu , sometimes I'll add 1 or 2 empty lines before the ending ` ``` ` by accident, because I could not see where the fenced codeblock ends.

I also respect the author's decision to hide unnecessary syntax from the markdown file. So I take a look and find out this [setting](https://github.com/ahmadawais/shades-of-purple-vscode/blob/v6.0.0/themes/shades-of-purple-color-theme.json#L1037) is changing the color of the ` ``` `.

As a result, I add the following setting to my VSCode `settings.json`. It's a good learning opportunity for me to learn more about VScode.

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "name": "make sure ``` in Shades of Purple theme is easier to see",
            "scope": [
                "punctuation.definition.markdown",
            ],
            "settings": {
                "foreground": "#79fafa88"
            }
        }
    ]
}
```

**Comment by ahmadawais** [comment]
That's an excellent choice, @comilao I'm working on a high contrast version as well. 👍
