### ISSUE TITLE
Consistent and contrasting text formatting within punctuation

### ISSUE THREAD

**Issue by rdhar** [ahmadawais/shades-of-purple-vscode#40]
First off, I'd like to commend you for your amazing work on the theme. The choice of colours complement each other incredibly well and the overall UI is really pleasing to the eye. Very well done!

I should mention, this isn't an "issue" as much a discussion about the theme and some potential ideas to enhance it further. I've attached a couple of screenshots at the end to give a visual comparison of what I'm talking about it.

1. For commented out lines, the preceding and subsequent punctuation gets italicised as well. Is this necessary? Does it not read better to leave the punctuation as is and only italicise the text that follows?
**E.g.**, For `<!-- HTML -->`, `/* CSS */`or `// JS`, I think it might read better to only italicise the text content within while leaving the punctuation marks on either side as regular since they don't tend to look as good, especially with ligatures.

1. For HTML tags, both the surrounding arrows and tag text are of the same colour. For better contrast legibility, would it not be better to have them as separate colours?
**E.g.**, `<div></div>` where both `<>` and the `div` share the same colour. What about contrasting colours instead, as with many other themes?

    1. I should add that I see you take this partially into account when formatting links in Markdown but only in certain circumstances. Perhaps it would be with making the contrasting colour consistent throughout?
    E.g., `[Content](www.site.link)` where the initial `[]` and `Content` are the same green colour (poor legibility contrast when scanning text quickly) whereas the secondary `()` is white and the `www.site.link` is cyan. This is perfect to separate out the punctuation from the actual text content that matters.
    Weirdly enough, for `[Content][file]`, the first set of `[]` shares the same colour as the text but the second set of `[]` is white in contrast of the red text within. While this is great for the second set of `[]`, it is inconsistent in the way it's formatted, as you can see from the screenshots attached below.

Here's the screenshots I mentioned that compare the formatting of a small variety of files running with Shades of Purple as well as another theme called [Palenight](https://github.com/whizkydee/vscode-material-palenight-theme). If you need any of the sample files shown in the screenshot for testing purposes, you can find them in this [Gist](https://gist.github.com/rdhar/65e2af74e5789d15355c156107547342).

![Shades of Purple](https://user-images.githubusercontent.com/19497993/57134857-584a4200-6d9f-11e9-825f-2d3693b9f828.png)
![Palenight Operator](https://user-images.githubusercontent.com/19497993/57134855-584a4200-6d9f-11e9-9617-ac93e1be3c71.png)

Please feel free to get back to me with any questions/feedback you have or if you'd like me to make smaller issues to address any of these separately. Thanks for your time!

**Comment by ahmadawais** [comment]
Howdy!

>First off, I'd like to commend you for your amazing work on the theme. The choice of colours complement each other incredibly well and the overall UI is really pleasing to the eye. Very well done!

That's very kind of you to say! 🙌

>I should mention, this isn't an "issue" as much a discussion about the theme and some potential ideas to enhance it further. I've attached a couple of screenshots at the end to give a visual comparison of what I'm talking about it.

Awesome! 💯


>>For commented out lines, the preceding and subsequent punctuation gets italicised as well. Is this necessary? Does it not read better to leave the punctuation as is and only italicise the text that follows?
E.g., For , /* CSS */or // JS, I think it might read better to only italicise the text content within while leaving the punctuation marks on either side as regular since they don't tend to look as good, especially with ligatures.

You can add the following token to do what you are saying here. I tried but that feels weird since a combination of _itallic_ and regular feels wrong.

```json
"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"name": "[NON-ITALICS] Comment's Punctuation.",
				"scope": [
					"punctuation.definition.comment",
				],
				"settings": {
					"fontStyle": ""
				}
			},
		]
	}
```

👆Make sure this is at the end of everything related to the theme token colors. 

Now reading further for #2.

**Comment by rdhar** [comment]
That's perfect, it looks exactly as I'd hoped with straight punctuation tags containing italicised text. Thank you!

![image](https://user-images.githubusercontent.com/19497993/57148409-75900800-6dc1-11e9-8029-7a1be8fb7244.png)

**Comment by ahmadawais** [comment]
>>For HTML tags, both the surrounding arrows and tag text are of the same colour. For better contrast legibility, would it not be better to have them as separate colours?
E.g., <div></div> where both <> and the div share the same colour. What about contrasting colours instead, as with many other themes?

I have seen different colors all over the place with almost every other theme. I don't much agree with that. I am a fan of making things minimal. So, to do that with HTML I chose the same color. That feels like one single element instead of it feeling like different elements with borders.

#### NOW: 

[!](https://on.ahmda.ws/4c9f30/url)

#### AFTER CHANGING TO YET ANOTHER COLORS: 

[!](https://on.ahmda.ws/04d679/url)


I feel that changing colors makes readability harder. With single color it feels like those divs are section makers with same single colors.

Again you can change that personally by changing the color here for this in your `settings.json` file.

```json
"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"name": "[HTML] - Color for HTML Tag",
				"scope": [
					"punctuation.definition.tag.begin.html",
					"punctuation.definition.tag.end.html",
				],
				"settings": {
					"foreground": "#A599E9"
				}
			},
		]
	}
```

For this reason, for now, I am going to keep it the same.

**Comment by ahmadawais** [comment]
>>I should add that I see you take this partially into account when formatting links in Markdown but only in certain circumstances. Perhaps it would be with making the contrasting colour consistent throughout?
E.g., [Content](www.site.link) where the initial [] and Content are the same green colour (poor legibility contrast when scanning text quickly) whereas the secondary () is white and the www.site.link is cyan. This is perfect to separate out the punctuation from the actual text content that matters.
Weirdly enough, for [Content][file], the first set of [] shares the same colour as the text but the second set of [] is white in contrast of the red text within. While this is great for the second set of [], it is inconsistent in the way it's formatted, as you can see from the screenshots attached below.

You are right. Markdown links were a mess. Mostly because I never made them look good and never had been the one using alternate link types (only now started doing that).

I am releasing a new update that makes the links, images, and their punctuation more fun to work with — and consistent. Thank you for pointing it out.

The next release has this:

![](https://on.ahmda.ws/d4d6b8/url)

```sh
Publishing ahmadawais.shades-of-purple@5.4.0...
 DONE  Published ahmadawais.shades-of-purple@5.4.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few seconds for it to show up).
```

**Comment by ahmadawais** [comment]
**DONE**: Published ahmadawais.shades-of-purple@5.4.0 that fixes this issue.

The theme will live at [https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) (might take a few seconds for it to show up).

Peace! ✌️

**Comment by rdhar** [comment]
>> For HTML tags, both the surrounding arrows and tag text are of the same colour. For better contrast legibility, would it not be better to have them as separate colours?
>
> I have seen different colors all over the place with almost every other theme. I don't much agree with that. I am a fan of making things minimal. So, to do that with HTML I chose the same color. That feels like one single element instead of it feeling like different elements with borders.

I think you might be absolutely correct here. Seeing the different colour arrows surrounding the tags, it does feel a little too busy at times. Still, your second version with the light-purple arrows _is_ quite relaxing as well :)

Thanks once again for sharing how to modify the colours from the User Settings. Makes it very easy to try out different ideas and settle on what works best. 👍

**Comment by ahmadawais** [comment]
>Still, your second version with the light-purple arrows is quite relaxing as well :)

You bet it does. I love that but whenever I try it I get overwhelmed. Not writing simple HTML anymore but in React it makes for a too much syntax.

>Thanks once again for sharing how to modify the colours from the User Settings. Makes it very easy to try out different ideas and settle on what works best. 👍

Sure thing. Shameless plug here but you can support my work via [VSCode Power User Course →](https://VSCode.pro)

This course is more about insights into my workflows than what the editor is about which makes it super fun.

Peace! ✌️

**Comment by rdhar** [comment]
Mainly for my own sake, here's an updated screenshot of my current configuration of your fantastic theme to compare against the first post in this thread. Thanks once again!

![image](https://user-images.githubusercontent.com/19497993/57399680-a6a97780-71c9-11e9-81df-21b68c0814fd.png)

<details><summary>View the changes made in User Settings (JSON)...</summary>
<pre>
{
  "workbench.colorCustomizations": {
    "breadcrumb.background": "#224",
    "editor.background": "#224",
    "editor.lineHighlightBackground": "#161632",
    "editor.lineHighlightBorder": "#161632",
    "editorHoverWidget.border": "#2D2B55",
    "editorGutter.background": "#224",
    "scrollbar.shadow": "#224",
    "statusBar.background": "#1E1E3F",
    "statusBar.border": "#224",
    "statusBar.debuggingBackground": "#1E1E3F",
    "statusBar.noFolderBackground": "#1E1E3F",
    "tab.activeBorder": "#0000",
    "tab.activeBorderTop": "#FAD000",
    "titleBar.activeBackground": "#2D2B55",
    "titleBar.activeForeground": "#FFF",
    "titleBar.inactiveBackground": "#2D2B55",
    "titleBar.inactiveForeground": "#A599E9"
  },
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "[HTML] Color - Tags",
        "scope": [
          "punctuation.definition.tag.begin.html",
          "punctuation.definition.tag.end.html",
          "punctuation.separator.key-value.css",
          "punctuation.separator.key-value.html"
        ],
        "settings": {
          "foreground": "#FB94FF"
        }
      },
      {
        "name": "[MARKDOWN] Color - Emphasis",
        "scope": ["markup.bold.markdown", "markup.italic.markdown"],
        "settings": {
          "foreground": "#FFF"
        }
      }
    ]
  }
}
</pre>
</details>

**Comment by yogithesymbian** [comment]
how to find list of all punctuation ? , i need to change from italic to normal for properties in tag html
