### ISSUE TITLE
Syntax highlighting for `.env` files

### ISSUE THREAD

**Issue by michaelborn** [ahmadawais/shades-of-purple-vscode#48]
Currently using [vscode-dotenv](https://github.com/mikestead/vscode-dotenv) for VSCode syntax highlighting of `.env` files.

Example syntax:

```
# This is a comment
API_KEY=blabla123
SMTP_SERVER=http://localhost/api
SMTP_PORT=465
```

**Comment by ahmadawais** [comment]
Thanks for reporting this. I have been meaning to address this.

![env](https://on.ahmda.ws/f591a7/url)

Fixed in 5.9.

 **DONE**  Published ahmadawais.shades-of-purple@5.9.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few seconds for it to show up).

**Comment by michaelborn** [comment]
Looks awesome Ahmad, thank you!

**Comment by ahmadawais** [comment]
Glad you liked it. Consider supporting my work throu https://VSCode.pro

> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_
