### ISSUE TITLE
inappropriate spacing caused unreadable text in quickpick

### ISSUE THREAD

**Issue by babul7154** [ahmadawais/shades-of-purple-vscode#63]
Hello Sir,I am using your theme for about 2-3 month,it is my favorite theme. I am a python/django developer.When I click a button at the bottom panel of vs code ,a pop-up list appears(it tells virtualenv Name and its path),but here the path of virtualenv is unreadable.when I tried the default theme and many other Theme then the problem is solved.Below is the screenshot.

**How I got this issue step 1>**
![14](https://user-images.githubusercontent.com/46845524/63120327-b9e59380-bfbf-11e9-8c3a-7d199d7fe235.PNG)

**Step 2 > pop-up list**
![15](https://user-images.githubusercontent.com/46845524/63120422-e5687e00-bfbf-11e9-8934-b03e24a14a3f.PNG)
**And after using other theme,no problem**

![13](https://user-images.githubusercontent.com/46845524/63120546-1c3e9400-bfc0-11e9-9a73-bafd2cad8ce8.PNG)

I have found same issue when try to configure python Framework.Please see the attachments.
![1](https://user-images.githubusercontent.com/46845524/63120612-3d9f8000-bfc0-11e9-90aa-9aadc07b4093.jpg)
![2](https://user-images.githubusercontent.com/46845524/63120613-3d9f8000-bfc0-11e9-923a-a7fdcb615faf.jpg)
![3](https://user-images.githubusercontent.com/46845524/63120614-3d9f8000-bfc0-11e9-9680-e48bcd450e1a.PNG)

**Comment by ahmadawais** [comment]
Can you share with me which extension is that? I have not been able to reproduce this issue. It's definitely not the theme's doing. Theme only makes things colorful, nothing to do with spacing.

**Comment by Esteban-Rocha** [comment]
@ahmadawais Hey! First of all thanks for the theme it is Awesome! I'm using it now as my primary theme.

I'll like to report that I'm getting the same issues as @babul7154 using this ext: [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus)

I confirm the issue seems to be with the theme as using other themes does not break the tooltip and it looks exactly like on @babul7154 screenshots.

**Comment by ahmadawais** [comment]
How can I reproduce this. Help me help you?

**Comment by Esteban-Rocha** [comment]
@ahmadawais Thanks for the quick response, just install the [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus) extension and it should add the `Project: Open` option at the command palette of VSCode.

By default the Ext. adds the shortcut 'Cmd/Ctrl+Alt+P' to trigger `Project: Open`

**Comment by ahmadawais** [comment]
I'm unable to get this extension to work. Not sure why.

This is what I get

![](https://on.ahmda.ws/9ffe30/c)

**Comment by Esteban-Rocha** [comment]
@ahmadawais Thanks for looking into this 👏, the `ext` got a critical bug since last week, there are already some reports on the issue tracker on the extension github [repository](https://github.com/fabiospampinato/vscode-projects-plus/issues/51), so let's wait Fabio to push a fix for it and as soon as that's done and you got some padding to look into this over the next couple of days/weeks I'm sure you'll be able to tackle that bug down.

Still best theme for Vscode so far, thanks again for the work 👌

**Comment by ahmadawais** [comment]
You might want to report this to the extension author's since theme has nothing to do with spacing. 🤔

Thanks for the kind words.
